version: '3'

services:
  db:
    image: postgis/postgis
    restart: always
    environment:
      - POSTGRES_DB=gestorx
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports: 
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data

  web:
    build: .
    volumes:
      - ../gestorx/:/code
      - ./requirements.txt:/code/requirements.txt
    command: bash -c "python -m pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      - db
